language: android

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - build-tools-24.0.0
    - android-24
    - platform-tools
    - extra-android-m2repository,extra-google-m2repository

script:
  ./gradlew build
