language: android

android:
  components:
    - tools
    - build-tools-23.0.3
    - android-23
    - platform-tools
    - extra-android-m2repository,extra-google-m2repository

script:
  ./gradlew build
